services:
  pros_soccer:
    image: kyehuang/pros_yolo:latest
    volumes:
      - ../src:/workspaces/src
    ports:
      - "9090:9090"
    networks:
      - my_bridge_network
    command: "./src/run.sh"

networks:
  my_bridge_network:
    driver: bridge